// Ref: https://www.tutorialspoint.com/kotlin
// https://play.kotlinlang.org/byExample/01_introduction/01_Hello%20world
// https://www.davideaversa.it/blog/kotlin-development-in-vscode/
// https://developer.ibm.com/tutorials/learn-kotlin-6/
/*
    Following are the different scenarios where Kotlin compiler will work differently.
    Compile Kotlin into bytecode which can run on JVM. This bytecode is exactly equal to the byte code generated by the Java .class file.
    Whenever Kotlin targets JavaScript, the Kotlin compiler converts the .kt file into ES5.1 and generates a compatible code for JavaScript.
    Kotlin compiler is capable of creating platform basis compatible codes via LLVM.
    Kotlin Multiplatform Mobile (KMM) is used to create multiplatform mobile applications with code shared between Android and iOS.

 */

/*
   Functions (methods in Java)
   ___________________________

   fun foo(pamam1: Int, param2: String): Unit {
      // Unit as the return type means "void"
   }
   Entry point for a kotlin application: main function

   Null Safety
   ___________

   As everything is an object in Kotlin (even Java primitive types),
   everything can be null.
   The way to specify that a variable can be null is by adding
   a question mark to the end of its type:
   val a: Int? = null

   Using the safe call operator (?.), the following line will
   only be executed if the variable is not null.
   Otherwise, it will do nothing:
   val a = b?.getValue()

   We can even provide an alternative for the null case using
   the Elvis operator (?:):
   val myString = a?.toString() ?: ""

   Variables
   _________
   var is a variable (mutable)
   val is a constant

   Data Type:
   Byte, Short (16 bit), Int, Long, Float, Double, Boolean

   Note that everything is an object in Kotlin (even Java primitive types)!

   Semicolon: optional
   ___________________
 */
import java.time.LocalDate
// Simple empty class
class Pippo
// Class with primary constructor (generate automaticalli attributes and getters)
// var attribute: cannot be modified (no setter)
class Person(val givenName: String, val familyName: String, val dateOfBirth: LocalDate)
// you can put extra code for constructor inside init{} block

// a data class is a class for holding data: it has automatically generated methods
// (toString, copy, equals, componentN(), ..)
data class User(val name: String, val age: Int)

// var attribute: generate getter and setter
class Animal(type: String, var breed: String) {

    // getter and setter for field in primary constructor
    public var type: String = type
    get() = field
    set(value) {
        field = value
    }

    private var age: Int = 0
    set(value) {  // setter for age
        if(value > 0)
            field = value
        else
            field = 0
    }
    // Secondary constructor
    constructor(type : String , breed :String, age :Int):this(type,breed) {
        if(age > 0)
            this.age = age
    }

}

fun main(args: Array<String>) {
    println("Hello World!")

    var msg: String = "Hello, World!" // defining a variable
    var msgAlt = "CheSuperSbomballo!"  // type inference
    var bool: Boolean = true  // a Boolean
    var boolNull: Boolean? = null  // a Boolean that can have null value
    println("$msg")  // print variable with $ sign
    println("message: "+msg)  // print variable in Java-like style

    val x: Int = 10000    // Integer (const)
    println("Int value is: "+x)

    val y: Long = x.toLong()   // Casting

    val numbers: IntArray = intArrayOf(1, 2, 3, 4, 5)   // Array (const)
    println("Value at 3rd position : " + numbers[2])
    numbers.set(2, 15)  // set a value
    // numbers.set(5, 25)  // Error! Out of bounds
    println("Value at 3rd position : " + numbers[2])

    val p = Person("Joe", "Doe", LocalDate.now())

    println(p.dateOfBirth.toString()+" "+p.givenName+" "+p.familyName)

    val animal = Animal("dog", "yorkshire")

    animal.type = "monkey";  // setter

    // Try adding program arguments via Run/Debug configuration.
    // Learn more about running applications: https://www.jetbrains.com/help/idea/running-applications.html.
    println("Program arguments: ${args.joinToString()}")
}